name: Electron/make

on: push

jobs:
  make:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node
        with:
          node-version: 20

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn make
