# https://dev.to/erikhofer/build-and-publish-a-multi-platform-electron-app-on-github-3lnd
name: Electron/publish
on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout

      - uses: actions/setup-node
        with:
          node-version: 20

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn publish
